[settings]
timeout = 1000
# provider = "Podman"

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"
[relaychain.default_resources]
limits = { memory = "2G", cpu = "2" }
requests = { memory = "1G", cpu = "1" }


  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]
  [relaychain.nodes.resources.limits]
  memory = "1G"
  cpu = "1"

  [relaychain.nodes.resources.requests]
  memory = "512Mi"
  cpu = "500m"

[[parachains]]
id = 100
addToGenesis = true

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"